# Numpy 기본 사용법 익히기
### 1. 패키지 불러오기

In [2]:
import csv
import numpy as np
import pandas as pd

### 2. Numpy 기본 사용법
#### 2.1. 기본 배열 생성
- `np.arange()` 함수 사용

In [3]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


- python의 range 함수와 비슷하게도 사용 가능

In [4]:
arr = np.arange(10, 30, 5)
print(arr)

[10 15 20 25]


---
#### 2.2. Numpy 2차원 배열 생성
- `np.arange()` 함수로 배열 생성 후 `reshape()`를 통해 2차원 배열로 변형

In [5]:
# reshape(행 개수, 열 개수)
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


---
#### 2.3. 특정 값으로 이루어진 배열 생성
- 0으로만 이루어진 배열 생성

In [6]:
# np.zeros((행 개수, 열 개수), dtype = 데이터 타입)
arr = np.zeros((3, 4), dtype=np.int64)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


- 1로만 이루어진 배열 생성

In [7]:
# np.ones((행 개수, 열 개수), dtype = 데이터 타입)
arr = np.ones((3, 4), dtype=np.int64)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


- 특정 수로 이루어진 배열 생성

In [8]:
# np.full((행 개수, 열 개수), 값)
arr = np.full((3, 4), 'a')
print(arr)

[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


---
#### 2.4. 균일한 간격의 숫자 생성
- `np.linspace()` 활용
- 그래프의 x축을 그릴 때 많이 사용

In [9]:
# np.linspace(구간 시작점, 구간 끝점, 구간 내 숫자 개수)
arr = np.linspace(-4, 4, 12)
print(arr)

[-4.         -3.27272727 -2.54545455 -1.81818182 -1.09090909 -0.36363636
  0.36363636  1.09090909  1.81818182  2.54545455  3.27272727  4.        ]


---
#### 2.5. 랜덤한 값 생성
- `np.random.rand()` 활용

In [11]:
# np.random.rand(개수)
arr = np.random.rand(7)
print(arr)

[0.68458765 0.20371134 0.21547531 0.01364601 0.21626658 0.12598336
 0.52369484]


- 2차원 배열로 생성

In [12]:
# np.random.rand(행 개수, 열 개수)
arr = np.random.rand(2, 3)
print(arr)

[[0.38117632 0.15375011 0.20507388]
 [0.09273058 0.72252085 0.27404194]]


- 원하는 범위 내의 정수 값을 원하는 개수로 생성

In [13]:
# np.random.randint(범위, size = 개수)
arr = np.random.randint(10, size = 6)
print(arr)

[8 0 8 0 6 0]


### 3. 기본 함수

In [15]:
arr = np.arange(15).reshape(3, 5)
print(arr.shape)  # 배열의 크기
print(arr.ndim)  # 배열의 차원
print(arr.dtype)  # 각 요소의 타입
print(arr.itemsize)  # 각 요소의 타입의 bytes의 크기
print(arr.size)  # 전체 요소의 개수

(3, 5)
2
int64
8
15


### 4. Indexing & Slicing
### 4.1. Indexing

In [16]:
arr = np.arange(25).reshape(5, 5)
print(arr[1][2])  # python의 기본 Indexing
print(arr[1, 2])  # ndarray에서의 Indexing

7
7


### 4.2. Slicing

In [17]:
arr = np.arange(25).reshape(5, 5)

In [18]:
# 1행 이상 3행 미만 / 2열 미만 출력
print(arr[1:3, :2])

[[ 5  6]
 [10 11]]


In [19]:
# 모든 행 / 2열 미만 출력
print(arr[:, :2])

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]


In [20]:
# 모든 행 / 모든 열을 2칸씩 띄워서 출력 
print(arr[:, ::2])

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [21]:
# 1행부터 끝까지 2칸씩 띄워서 / 0열부터 4열 미만까지 3칸씩 띄워서 출력
print(arr[1::2, 0:4:3])

[[ 5  8]
 [15 18]]


### 5. 배열 값 수정 & 복사
- 얕은 복사에 주의
  - 깊은 복사 : '실제 값'을 새로운 메모리 공간에 복사하는 것
  - 얕은 복사 : '주소 값'을 복사
- 원본 배열을 수정하지 않으려면 `np.copy()` 함수를 사용

In [22]:
arr = np.arange(15).reshape(3, 5)

# arr의 값도 함께 변경됨
arr2 = arr
arr2[0][0] = 15
print(arr)  

[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [24]:
# arr의 값은 그대로 출력
arr = np.arange(15).reshape(3, 5)
arr2 = arr.copy()
arr2[0][0] = 15
print(arr)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
